pid_maze_solver:
  ros__parameters:
    waypoints_sim: [0.6, 0.0, -0.7854,
                    0.3, -0.32, 0.7854,
                    0.47, 0.0, 0.0,
                    0.0, 0.33, 0.0,
                    0.465, 0.0, -1.5708,
                    0.0, -0.835, 0.0,
                    -0.55, 0.0, 0.0,
                    0.0, -0.567, 0.0,
                    -0.38, 0.0, 0.0,
                    0.0, -0.51, -1.5708,
                    -0.52, 0.0, -1.5708,
                    0.0, 1.17, 0.7854,
                    -0.185, 0.18, 0.7854,
                    -0.31, 0.0, 3.1415]