pid_maze_solver:
  ros__parameters:
    waypoints_sim: [0.335, 0.0, -0.7854,
                    0.185, -0.18, -0.7854,
                    0.0, -1.15, 1.5708,
                    0.52, 0.0, 1.5708,
                    0.0, 0.5, 0.0,
                    0.38, 0.0, 0.0,
                    0.0, 0.567, 0.0,
                    0.55, 0.0, 0.0,
                    0.0, 0.82, 1.5708,
                    -0.465, 0.0, 0.0,
                    0.0, -0.33, 0.0,
                    -0.465, 0.0, -0.7854,
                    -0.3, 0.32, 0.7854,
                    -0.6, 0.0, 3.1415]